### ISSUE TITLE
Scriptfehler bzw. leere Ordner

### ISSUE THREAD

**Issue by remogor** [s0faking/plugin.video.puls4#1]
Hallo!

Ich erhalte bei Nutzung deines Pulse4-Addons einen Scriptfehler bzw. sind die Ordner leer.

Hier ist der Link zu meinem Log:
http://xbmclogs.com/show.php?id=322783

Wäre super, wenn du dir das ansehen könntest!
Danke

**Comment by s0faking** [comment]
Hi,

hab das addon schon lang nicht mehr am laufen gehabt. ich werds mir die 
tage mal ansehen. da hat sich wohl an der website was geändert. danke 
fürs feedback

lg

Am 21.10.2014 um 12:14 schrieb remogor:

> Hallo!
> 
> Ich erhalte bei Nutzung deines Pulse4-Addons einen Scriptfehler bzw. 
> sind die Ordner leer.
> 
> Hier ist der Link zu meinem Log:
> http://xbmclogs.com/show.php?id=322783
> 
> Wäre super, wenn du dir das ansehen könntest!
> Danke
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/s0faking/plugin.video.puls4/issues/1.

## 

  -=[============]=-

```
.lowfidelity
```

   Daniel Weidacher

[Senior Bootstrapper]

  www.lowfidelity.at
  dw@lowfidelity.at

   +43 1 9417809
  -=[============]=-

**Comment by tschoartschi** [comment]
Hallo!

Wollte das Plugin auch ausprobieren. Aber ich bin mir fast sicher, dass es daran liegt, dass sich die Website geändert hat. Schade, aber das ORF plugin von @s0faking  funktioniert prima :)

**Comment by s0faking** [comment]
Hi,

habs mir mal kurz angesehen. das Problem ist das sich da die Puls4 Mediathek an die Seven Media Mediathek angepasst hat, sprich anscheinend verwenden die jetzt dasselbe Frontend wie zB ProSieben. Leider komm ich grad zeittechnisch zu gar nix aber ich reihs mal in meine lange Todo Liste ein ;) danke für die blumen @tschoartschi .

**Comment by tschoartschi** [comment]
Man darf ja auch mal Lob austeilen ;-) bin wirklich zufrieden mit dem ORF Plugin und seit du die Issue mit dem beautiful soup [[1](https://github.com/s0faking/plugin.video.orftvthek/issues/1)] gelöst hast, läufts auch am Raspberry super. Ich hoffe du findest auch mal Zeit fürs Puls4 Plugin. Bei mir ists zeittechnisch auch gerade knapp, ansonsten könnte ich Hilfe anbieten.

**Comment by s0faking** [comment]
so...hab gestern ne kleine nachschicht eingelegt. sollte jetzt wieder klappen.

**Comment by remogor** [comment]
vielen dank!!
funktioniert einwandfrei.
;-D

**Comment by tschoartschi** [comment]
Funktioniert auch am Raspberry Pi 1b super :) riesiges Danke

**Comment by s0faking** [comment]
perfekt. das addon is jetzt unterwegs ins official repo
