### ISSUE TITLE
Sports live stream not working

### ISSUE THREAD

**Issue by GutHib** [s0faking/plugin.video.puls4#6]
Unfortunately, the NFL live stream isn't working. It shows up in the sports category, but after clicking on it, it just tells you "Dieses Video steht momentan nicht zur Verfügung" while at the same time, clicking on the same stream via web browser works just fine.

Not sure if this helps, but this used to be fine 2 (?) years ago.

Thanks, and keep up the great work!

**Comment by s0faking** [comment]
sports stream is behind drm and not accessible afaik
